### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Mustafa-Kamel**
Take a look at the added files in pages/Courses_Projects path:
- CoursesProjectsModel
- CoursesController
- ProjectsController

### CODE REVIEW

**Comment by mahmoudShaheen** [comment]
i think functions are good, but pages are required as we discussed in our last meeting.
please make the required pages are re-send a pull request.
**Note:**
you may use this as a reference
[Bade3 pull request](https://github.com/mahmoudShaheen/SocialNetwork/pull/3)

**Comment by Mustafa-Kamel** [comment]
But I think that's better than having each function in a detached file [that's your thought], the same thing in a different manner.

> You shouldn't think, you must believe.

Trust me, that's not going to matter.

**Comment by mahmoudShaheen** [comment]
i didn't mean that each function should be in a file. 😂 
you can put all the functions in one file if you want, what i meant is you still have to implement the pages needed which will call these functions.

**course:**
- add/edit
- view
**projects:**
- add/edit
- view

**Comment by Mustafa-Kamel** [comment]
Ok, I have no problem with that.
I mentioned how to call them and explained how easy is it, so I thought that was sufficient and they would be created after finishing the site design.

**Comment by mahmoudShaheen** [comment]
The problem is that front end team will use these pages which we provide to design the website, and they don't know that much about PHP.
so we have to echo all page content then they will add HTML, CSS, JS required for design.

**Pull request merged**
